name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  deployments: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
    
  benchmark:
    name: Run Benchmark.Net benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Run benchmark
        run: cd src/ApplicationBenchmark && dotnet run --configuration Release --exporters json --filter '*'

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.Net Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: src/ApplicationBenchmark/BenchmarkDotNet.Artifacts/results/Sample.Benchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@rebeccapowell'